export const actionTypes={
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT",
    INCREMENT_BY_FIVE:"INCREMENT_BY_FIVE",
    DECREMENT_BY_FIVE:"DECREMENT_BY_FIVE",
    CHANGE_NAME:"CHANGE_NAME",
    SAVE_USER:"SAVE_USER",
    SHOW_USER:"SHOW_USER"
}